backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "reps"
    label: "Repetition"
    folder: "_reps"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Bild", name: "image", widget: "image" }
      - label: "LÃ¥tar"
        name: "tracks"
        widget: "list"
        fields:
          - { label: "MP3", name: "url", widget: "file" }
